[tool.poetry]
name = "repl_python3_Lsw"
version = "0.1.0"
description = ""
authors = ["otiopo <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
GPUtil = "^1.4.0"
psutil = "^5.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
